# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zfgAhWoDpiqY0j1fs52m-E2Z4cIdH0T
"""

import re
import random
from datetime import datetime

class TraditionalRuleBasedChatbot:
    def __init__(self):
        self.bot_name = "Student Support Bot"

        self.intents = {
            "greeting": {
                "keywords": ["hi", "hello", "hey", "good morning", "good evening"],
                "responses": [
                    "Hello! I am Student Support Bot. Type 'help' to see what I can do.",
                    "Hi there! I can help with course, assignment, and chatbot project questions."
                ]
            },
            "help": {
                "keywords": ["help", "capabilities", "what can you do", "options", "menu"],
                "responses": [
                    """I can help with:
1. Course information
2. Assignment requirements
3. Due date questions
4. Chatbot explanation
5. Contact/support guidance
6. Current date and time

Try asking: 'What is this assignment about?' or 'What is a chatbot?'"""
                ]
            },
            "assignment": {
                "keywords": ["assignment", "project", "report", "apa", "github", "zip", "course"],
                "responses": [
                    "This project requires creating a simple traditional chatbot, documenting the development lifecycle, submitting a 5-7 page APA report, a ZIP archive, and a GitHub URL."
                ]
            },
            "chatbot_definition": {
                "keywords": ["what is chatbot", "chatbot meaning", "define chatbot"],
                "responses": [
                    "A chatbot is a software program that simulates conversation with users. This chatbot uses traditional rule-based logic instead of an LLM."
                ]
            },
            "traditional": {
                "keywords": ["rule based", "traditional", "non llm", "without ai", "keyword"],
                "responses": [
                    "A rule-based chatbot uses predefined rules, keywords, and fixed responses. It does not learn from data and does not use large language models."
                ]
            },
            "deadline": {
                "keywords": ["deadline", "due", "submit", "submission"],
                "responses": [
                    "Please check the course portal for the exact deadline. The submission should include the APA report, GitHub URL, and ZIP file."
                ]
            },
            "contact": {
                "keywords": ["contact", "instructor", "professor", "support", "email"],
                "responses": [
                    "For official questions, contact your instructor or check the course announcements."
                ]
            },
            "time": {
                "keywords": ["time", "date", "today"],
                "responses": [
                    f"The current date and time is {datetime.now().strftime('%B %d, %Y %I:%M %p')}."
                ]
            },
            "goodbye": {
                "keywords": ["bye", "goodbye", "exit", "quit"],
                "responses": [
                    "Goodbye! Good luck with your chatbot project."
                ]
            }
        }

    def clean_input(self, user_input):
        user_input = user_input.lower().strip()
        user_input = re.sub(r"[^a-zA-Z0-9\s]", "", user_input)
        return user_input

    def detect_intent(self, user_input):
        cleaned = self.clean_input(user_input)

        if cleaned == "":
            return "empty"

        for intent, data in self.intents.items():
            for keyword in data["keywords"]:
                if keyword in cleaned:
                    return intent

        return "unknown"

    def get_response(self, user_input):
        intent = self.detect_intent(user_input)

        if intent == "empty":
            return "Please type a question or type 'help' to see my capabilities."

        if intent == "unknown":
            return "Sorry, I did not understand that. Type 'help' to see what I can answer."

        return random.choice(self.intents[intent]["responses"])

    def start_chat(self):
        print("=" * 60)
        print(f"Welcome to {self.bot_name}")
        print("This is a traditional rule-based chatbot.")
        print("Type 'help' for options or 'exit' to quit.")
        print("=" * 60)

        while True:
            user_input = input("You: ")
            response = self.get_response(user_input)
            print("Bot:", response)

            if self.detect_intent(user_input) == "goodbye":
                break


bot = TraditionalRuleBasedChatbot()
bot.start_chat()

from google.colab import drive
drive.mount('/content/drive')